SourceLabOrg/kafka-webview

CHANGELOG.md, Dockerfile, kafka-webview-plugin/pom.xml, kafka-webview-ui/pom.xml, kafka-webview-ui/src/main/java/org/sourcelab/kafka/webview/ui/configuration/SecurityConfig.java, kafka-webview-ui/src/main/java/org/sourcelab/kafka/webview/ui/controller/configuration/view/ViewConfigController.java, kafka-webview-ui/src/test/java/org/sourcelab/kafka/webview/ui/controller/configuration/filter/FilterConfigControllerTest.java, kafka-webview-ui/src/test/java/org/sourcelab/kafka/webview/ui/controller/configuration/view/ViewConfigControllerTest.java, kafka-webview-ui/src/test/java/org/sourcelab/kafka/webview/ui/tools/FilterTestTools.java, pom.xml
=> [ISSUE43] - Fix bug in view config controller when creating new view

CHANGELOG.md, Dockerfile, kafka-webview-plugin/pom.xml, kafka-webview-ui/pom.xml, kafka-webview-ui/src/main/resources/config/base.yml, pom.xml
Short term fix for #53 - Increase file upload limit.
=> [ISSUE-53] Increase file upload limit

CHANGELOG.md, kafka-webview-ui/pom.xml, pom.xml
- Update SpringBoot dependency from 1.5.6 to 1.5.10.
- Update Logback dependency from 1.1.11 to 1.2.3.
=> Update SpringBoot release version

kafka-webview-ui/src/main/java/org/sourcelab/kafka/webview/ui/manager/kafka/dto/TopicList.java, kafka-webview-ui/src/test/java/org/sourcelab/kafka/webview/ui/manager/kafka/dto/TopicListTest.java
=> [ISSUE-71] Sort topics in select boxes

kafka-webview-ui/src/main/java/org/sourcelab/kafka/webview/ui/manager/Utils.java, kafka-webview-ui/src/main/java/org/sourcelab/kafka/webview/ui/model/View.java, kafka-webview-ui/src/main/resources/templates/configuration/view/index.html, kafka-webview-ui/src/main/resources/templates/view/index.html, kafka-webview-ui/src/test/java/org/sourcelab/kafka/webview/ui/manager/UtilsTest.java
=> [ISSUE-74] display better partition list on datatables

kafka-webview-ui/src/main/java/org/sourcelab/kafka/webview/ui/controller/configuration/user/UserController.java
=> [ISSUE-72] add missing attr

CHANGELOG.md, kafka-webview-ui/src/main/java/org/sourcelab/kafka/webview/ui/manager/plugin/PluginFactory.java, kafka-webview-ui/src/main/java/org/sourcelab/kafka/webview/ui/manager/plugin/exception/LoaderException.java
=> [Issue-81] Gracefully handle missing dependencies.

CHANGELOG.md, kafka-webview-ui/src/main/frontend/css/style.css, kafka-webview-ui/src/main/resources/templates/stream/index.html, kafka-webview-ui/src/main/resources/templates/view/consume.html
=> [Issue-83] Add overflow scroll

Dockerfile, README.md
- Simplify Dockerfile. 
- Add sha1 validation of DLed package from Github.
=> Update docker file

CHANGELOG.md, README.md, kafka-webview-ui/src/assembly/distribution/config.yml, kafka-webview-ui/src/main/java/org/sourcelab/kafka/webview/ui/configuration/AppProperties.java, kafka-webview-ui/src/main/java/org/sourcelab/kafka/webview/ui/configuration/SecurityConfig.java, kafka-webview-ui/src/main/java/org/sourcelab/kafka/webview/ui/controller/BaseController.java, kafka-webview-ui/src/main/java/org/sourcelab/kafka/webview/ui/manager/user/AnonymousUserDetailsService.java, kafka-webview-ui/src/main/java/org/sourcelab/kafka/webview/ui/manager/user/CustomUserDetailsService.java, kafka-webview-ui/src/main/resources/config/base.yml, kafka-webview-ui/src/main/resources/config/dev.yml, kafka-webview-ui/src/test/java/org/sourcelab/kafka/webview/ui/controller/configuration/view/ViewConfigControllerAnonymousUserTest.java, kafka-webview-ui/src/test/resources/application.yml, pom.xml
Add new configuration option that can disable all user authentication by the web app.  Setting this option will allow all anonymous users access to the web interface with ADMIN credentials.
In part for issue #85 .
=> First pass at making user authentication optional via configuration option.

CHANGELOG.md, README.md, kafka-webview-ui/src/assembly/distribution/config.yml, kafka-webview-ui/src/main/resources/config/base.yml
=> [ISSUE-103] More explicitly expose user session timeout value

CHANGELOG.md, dev-cluster/pom.xml, kafka-webview-plugin/pom.xml, kafka-webview-ui/pom.xml, kafka-webview-ui/src/main/java/org/sourcelab/kafka/webview/ui/controller/stream/StreamController.java, kafka-webview-ui/src/main/resources/templates/layout.html, kafka-webview-ui/src/test/java/org/sourcelab/kafka/webview/ui/controller/login/AnonymousLoginTest.java, kafka-webview-ui/src/test/java/org/sourcelab/kafka/webview/ui/controller/stream/AbstractStreamControllerTest.java, kafka-webview-ui/src/test/java/org/sourcelab/kafka/webview/ui/controller/stream/StreamControllerAnonymousUserAuthenticationTest.java, kafka-webview-ui/src/test/java/org/sourcelab/kafka/webview/ui/controller/stream/StreamControllerLdapUserAuthenticationTest.java, kafka-webview-ui/src/test/java/org/sourcelab/kafka/webview/ui/controller/stream/StreamControllerLocalUserAuthenticationTest.java, kafka-webview-ui/src/test/java/org/sourcelab/kafka/webview/ui/controller/stream/StreamControllerTest.java, kafka-webview-ui/src/test/java/org/sourcelab/kafka/webview/ui/tools/MessageFormatTestTools.java, kafka-webview-ui/src/test/java/org/sourcelab/kafka/webview/ui/tools/ViewTestTools.java, kafka-webview-ui/src/test/java/org/sourcelab/kafka/webview/ui/tools/integration/UserLoginUtility.java, pom.xml
Fix for #127 
Stream consumers are broken for anonymous user access.  Lets add some integration tests over the stream controller endpoints, then resolve the underlying error.
=> [Issue-127] fix anonymous user access to streams

CHANGELOG.md, kafka-webview-ui/src/main/frontend/gulp-tasks/build-dist.js, kafka-webview-ui/src/main/frontend/js/app.js, kafka-webview-ui/src/main/resources/config/dev.yml, kafka-webview-ui/src/main/resources/templates/404.html, kafka-webview-ui/src/main/resources/templates/cluster/read.html, kafka-webview-ui/src/main/resources/templates/cluster/readBroker.html, kafka-webview-ui/src/main/resources/templates/cluster/readTopic.html, kafka-webview-ui/src/main/resources/templates/configuration/cluster/create.html, kafka-webview-ui/src/main/resources/templates/error.html, kafka-webview-ui/src/main/resources/templates/layout.html, kafka-webview-ui/src/main/resources/templates/login.html
Follow-up PR for #136 to adjust Javascript generated URLs to be appropriately prefixed.
Reverts Font-Awesome font paths to be relative instead of fixed absolute references.
=> Follow up PR for ISSUE-136

CHANGELOG.md, dev-cluster/pom.xml, kafka-webview-plugin/pom.xml, kafka-webview-ui/pom.xml, kafka-webview-ui/src/main/resources/templates/stream/index.html, pom.xml
=> [ISSUE-143] Fix stream connection URLs when running behind a reverse proxy with a prefix

.travis.yml, README.md
#155 Create documentation detailing how to run Kafka-webview behind a reverse proxy + prefixed URL
=> #155 Create documentation detailing how to run Kafka-webview behind a reverse proxy + prefixed URL

kafka-webview-ui/src/main/java/org/sourcelab/kafka/webview/ui/manager/kafka/KafkaConsumerFactory.java, kafka-webview-ui/src/main/java/org/sourcelab/kafka/webview/ui/manager/kafka/ParallelWebKafkaConsumer.java
Updates multi-threaded client to create and re-use existing client where possible.
=> Create and reuse kafka client where possible

CHANGELOG.md, kafka-webview-ui/src/main/java/org/sourcelab/kafka/webview/ui/configuration/DataLoaderConfig.java, kafka-webview-ui/src/main/java/org/sourcelab/kafka/webview/ui/manager/kafka/deserializer/BytesToHexDeserializer.java, kafka-webview-ui/src/main/java/org/sourcelab/kafka/webview/ui/manager/plugin/PluginFactory.java, kafka-webview-ui/src/main/java/org/sourcelab/kafka/webview/ui/manager/plugin/UploadManager.java, kafka-webview-ui/src/test/java/org/sourcelab/kafka/webview/ui/manager/kafka/WebKafkaConsumerFactoryTest.java, kafka-webview-ui/src/test/java/org/sourcelab/kafka/webview/ui/manager/kafka/deserializer/BytesToHexDeserializerTest.java
Adds a built-in deserializer that 'decodes' bytes into hex string values.  for #190
=> Add "user friendly" bytes deserializer

CHANGELOG.md, kafka-webview-ui/src/main/java/org/sourcelab/kafka/webview/ui/controller/stream/StreamController.java, kafka-webview-ui/src/main/resources/templates/fragments/consumerSetting/partitionFilter.html, kafka-webview-ui/src/main/resources/templates/fragments/consumerSetting/recordFilter.html, kafka-webview-ui/src/main/resources/templates/stream/index.html, kafka-webview-ui/src/main/resources/templates/view/consume.html
for #161 
Adds dedicated `Apply` and `Reset` buttons to partition and record filters.
=> [ISSUE-161] Add dedicated apply and reset button to filters

kafka-webview-ui/src/main/java/org/sourcelab/kafka/webview/ui/controller/configuration/cluster/ClusterConfigController.java, kafka-webview-ui/src/main/java/org/sourcelab/kafka/webview/ui/manager/kafka/KafkaOperations.java, kafka-webview-ui/src/main/java/org/sourcelab/kafka/webview/ui/manager/kafka/dto/ApiErrorResponse.java, kafka-webview-ui/src/main/java/org/sourcelab/kafka/webview/ui/manager/ui/FlashMessage.java, kafka-webview-ui/src/main/resources/templates/fragments/alert.html
=> Add ability to show stack traces in danger alerts

CHANGELOG.md, dev-cluster/pom.xml, dev-cluster/startDevCluster.sh, generateDummySslCertificates.sh, kafka-webview-ui/pom.xml, kafka-webview-ui/src/main/frontend/package-lock.json, pom.xml
Updates Java based dependencies to resolve security advisories.
Follow up PR to update javascript/npm dependencies to come.
for #244
=> Update Java dependencies to resolve security issues.

CHANGELOG.md, dev-cluster/pom.xml, kafka-webview-plugin/pom.xml, kafka-webview-ui/pom.xml, kafka-webview-ui/src/main/java/org/sourcelab/kafka/webview/ui/configuration/PluginConfig.java, kafka-webview-ui/src/main/resources/config/base.yml, kafka-webview-ui/src/test/java/org/sourcelab/kafka/webview/ui/manager/kafka/dto/ConsumerGroupOffsetsTest.java, pom.xml
Upgrade the project thru each version of SpringBoot from 2.2 through 2.6 and validate behavior.  End goal is to have the project running on the latest version of SpringBoot if possible.
=> Upgrade from Springboot 2.1 to 2.6

kafka-webview-ui/src/main/resources/config/base.yml
Fixes# https://github.com/SourceLabOrg/kafka-webview/issues/235
=> fix(yml) : corrected  the spelling ACTUATOR_PORT

CHANGELOG.md, dev-cluster/pom.xml, kafka-webview-plugin/pom.xml, kafka-webview-ui/pom.xml, pom.xml
=> Prepare for release of 2.9.1
